# ansible 127.0.0.1 -m apt -a 'name=nginx state=present' -b

- hosts: localhost
  become: true
  tasks:
  - name: create a directory which should cause a failure 
    command: mkdir /var/testdir1
    register: mkdir_output_var
    failed_when: "'File exists' not in mkdir_output_var.stderr and mkdir_output_var.rc != 0 "

  - name: Install nginx httpd  (state=present is optional)
    apt:
      #name: nginx=1.18.0
      name: nginx
      state: present
  - name: Install my super ace website
    copy:
      content: 'This is my ansible deployed Web Server Using Nginx'
      dest: /var/www/html/index.html 
  - name: Create a directory in the webserver
    file:
      path: /var/www/html/subdirectory
      state: directory
      mode: '0755'
  - name: Ensure nginx is started and enabled
    systemd:
      name: nginx.service
      state: started
      enabled: yes
    register: systemd_task_var
  - name: debug the previous task
    debug:
      var: systemd_task_var 
  - name: run some command for the lols
    command: grep ubuntu /etc/passwd
    register: command_output_var
  - name: Use debug to print the registerd variable
    debug:
      msg: Here is the output from the previous task {{ command_output_var.stdout }}
  - name: run a shell, we can use pipe and redirects and stuff
    shell:
      cmd: grep ubuntu /etc/passwd >> /var/www/html/index.html
