- name: uninstall
  hosts: localhost
  become: true
  tasks:
          - name: uninstall
            apt:
                    name: nginx
                    state: absent
                    autoremove: yes
