---
# tasks file for ansibleexercise
- name: Clone down a git repo that was specified
  git:
    repo: {{ exercise_git_repo }}
    dest: /var/gitrepo
- name: create file with host ip in it
  copy:
    content: "{{ ansible_default_ipv4.address }}"
    dest: /var/ansible-ip-address-file
- name: Print a message on the console if this is an Ubuntu OS
  debug:
    msg: "This is a message that will be printed if the host OS is ubuntu"
  when: ansible_distribution == "Ubuntu"